# First Map Template Repository

<https://github.com/cu-esiil-edu/first-map-template>

A template repository for getting started with map-making in GitHub Codespaces.

To use:

  1. Click on `Use this Template` in the upper right, and select `Open in Codespace`. This might take a minute if you haven't done it in awhile.
  2. Once the Codespace loads, open `first-map.ipynb`
  3. Complete the activity
  4. Find your map in the left-hand file explorer, click on the `...` and download your map.
  5. [Stop your Codespace](https://docs.github.com/en/codespaces/developing-in-a-codespace/stopping-and-starting-a-codespace#stopping-a-codespace) so you don't use up your allocation!
  
# Add a map to your website

Get started with maps

Nate Quarderer  
Elsa Culler  
2024-03-28

## Get started with map-making using open-sources tools

### Finding locations and boundaries

[Open Street Map (OSM)](https://www.openstreetmap.org/) is an
open-source, editable map of the world – a little like a wiki for
places. They also provide a service for looking up locations using text,
which we’ll be using in this activity.

```{python child = "Python/first_map_library.py"}
```

### Search for a point of interest

You can use the `pyrosm` package to download and search for spatial
vector data in your area, or anywhere around the world.

In this case, we’re looking for the location of the United Tribes
Technical College campus in North Dakota. The address in here,
`'United Tribes Technical College, Bismarck, ND, United States'`, does
not have to be complete or exact, but it should be specific enough to
narrow it down. We are also specifying that we want it to be tagged as an
`'amentity'` type, specifically a `'college'` You might have to try a
couple different searches with different addresses and/or tags to get
the address you want, just like if you are using a map website or app.

```{python child = "Python/first_map_uttc.py"}
```

We have a map of the UTTC Campus!

> **Warning**
>
> The Open Street Maps (OSM) database is not always complete. For
> example, try searching for UTTC with the `{'building': True}`, and
> compare it to the [map of the UTTC campus on their
> website](https://uttc.edu/wp-content/uploads/2022/12/CAMPUS-MAP-2022-23.pdf).
> What do you notice?

### Create an interactive map

There are lots of different ways to create maps and plots in Python.
Here, we’re going to use a tool called `'hvplot'` and `'geoviews'` to
create an interactive map, including the online `'EsriImagery'` tile
source basemap.

```{python child = "Python/first_map_interact.py"}
```

### Download your map from Codespaces

If you are doing this activity on GitHub Codespaces, you will need to download the map you created:

1. Open the Folders tab on the left hand side
2. Right-click on uttc.html (or whatever you named your file)
3. Select Download...

This should download your map.

### Place your map in your webpage

You are now ready to upload your map to your portfolio repository and place it in your webpage. Because it is HTML and not an image, you will need to use the following HTML to get it on your page:

```
<embed type="text/html" src="uttc.html" width="600" height="600">
```